import type { Discipline, Activity, DayLog } from "../types";

export const DEFAULT_DISCIPLINES: Discipline[] = [
  { id: "physical", name: "Fisico", color: "#e74c3c" },
  { id: "mind", name: "Mente", color: "#3b82f6" },
  { id: "charm", name: "Charm", color: "#a855f7" },
  { id: "spirit", name: "Spirito", color: "#22c55e" },
];

export const DEFAULT_ACTIVITIES: Activity[] = [
  {
    id: "running",
    disciplineId: "physical",
    name: "Corsa",
    points: 2,
    hasCounter: false,
  },
  {
    id: "gym",
    disciplineId: "physical",
    name: "Palestra / Calisthenics",
    points: 2,
    hasCounter: false,
  },
  {
    id: "abs",
    disciplineId: "physical",
    name: "Addominali",
    points: 1,
    hasCounter: false,
  },
  {
    id: "stretching",
    disciplineId: "physical",
    name: "Stretching",
    points: 1,
    hasCounter: false,
  },
  {
    id: "cheat",
    disciplineId: "physical",
    name: "Sgarro",
    points: -1,
    hasCounter: true,
  },

  {
    id: "reading",
    disciplineId: "mind",
    name: "Lettura 30 min",
    points: 2,
    hasCounter: false,
  },
  {
    id: "deep-work",
    disciplineId: "mind",
    name: "Deep work 90 min",
    points: 3,
    hasCounter: false,
  },
  {
    id: "language",
    disciplineId: "mind",
    name: "Pratica lingua",
    points: 2,
    hasCounter: false,
  },
  {
    id: "doomscroll",
    disciplineId: "mind",
    name: "Doomscroll",
    points: -1,
    hasCounter: false,
  },

  {
    id: "diction",
    disciplineId: "charm",
    name: "Dizione",
    points: 2,
    hasCounter: false,
  },
  {
    id: "music",
    disciplineId: "charm",
    name: "Musica",
    points: 2,
    hasCounter: false,
  },
  {
    id: "driving-license",
    disciplineId: "charm",
    name: "Patente (1h o quiz)",
    points: 1,
    hasCounter: false,
  },

  {
    id: "meditation",
    disciplineId: "spirit",
    name: "Meditazione",
    points: 2,
    hasCounter: false,
  },
  {
    id: "journaling",
    disciplineId: "spirit",
    name: "Journaling",
    points: 1,
    hasCounter: false,
  },
  {
    id: "nature",
    disciplineId: "spirit",
    name: "Tempo in natura",
    points: 1,
    hasCounter: false,
  },
];

export const DEFAULT_DAY_LOGS: DayLog[] = [
  { date: "2026-03-08", entries: [{ activityId: "running", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-09", entries: [{ activityId: "gym", count: 1 }, { activityId: "abs", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-10", entries: [{ activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-03-11", entries: [{ activityId: "stretching", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "guitar", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-03-12", entries: [{ activityId: "gym", count: 1 }, { activityId: "doomscroll", count: 1 }] },
  { date: "2026-03-13", entries: [{ activityId: "running", count: 1 }, { activityId: "abs", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-14", entries: [{ activityId: "cheat", count: 2 }, { activityId: "reading", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-03-15", entries: [{ activityId: "gym", count: 1 }, { activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "singing", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-16", entries: [{ activityId: "abs", count: 1 }, { activityId: "stretching", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "driving-license", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-03-17", entries: [{ activityId: "deep-work", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "guitar", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-03-18", entries: [{ activityId: "running", count: 1 }, { activityId: "gym", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "language", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-03-19", entries: [{ activityId: "cheat", count: 1 }, { activityId: "doomscroll", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-20", entries: [{ activityId: "running", count: 1 }, { activityId: "abs", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "dancing", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-03-21", entries: [{ activityId: "stretching", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "guitar", count: 1 }, { activityId: "singing", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-03-22", entries: [{ activityId: "gym", count: 1 }, { activityId: "language", count: 1 }, { activityId: "driving-license", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-23", entries: [{ activityId: "running", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-03-24", entries: [{ activityId: "abs", count: 1 }, { activityId: "stretching", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "expressions", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-25", entries: [{ activityId: "gym", count: 1 }, { activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "dancing", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-03-26", entries: [{ activityId: "cheat", count: 2 }, { activityId: "reading", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-03-27", entries: [{ activityId: "running", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "guitar", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-28", entries: [{ activityId: "gym", count: 1 }, { activityId: "abs", count: 1 }, { activityId: "language", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-03-29", entries: [{ activityId: "running", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "singing", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-03-30", entries: [{ activityId: "stretching", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "driving-license", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-03-31", entries: [{ activityId: "gym", count: 1 }, { activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "doomscroll", count: 1 }] },
  { date: "2026-04-01", entries: [{ activityId: "running", count: 1 }, { activityId: "abs", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-04-02", entries: [{ activityId: "gym", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-03", entries: [{ activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "guitar", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-04-04", entries: [{ activityId: "abs", count: 1 }, { activityId: "stretching", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "expressions", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-04-05", entries: [{ activityId: "cheat", count: 1 }, { activityId: "doomscroll", count: 1 }] },
  { date: "2026-04-06", entries: [{ activityId: "gym", count: 1 }, { activityId: "running", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-07", entries: [{ activityId: "stretching", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "language", count: 1 }, { activityId: "dancing", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-04-08", entries: [{ activityId: "running", count: 1 }, { activityId: "abs", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-09", entries: [{ activityId: "gym", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "guitar", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-04-10", entries: [{ activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "singing", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-04-11", entries: [{ activityId: "abs", count: 1 }, { activityId: "stretching", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-12", entries: [{ activityId: "cheat", count: 2 }, { activityId: "reading", count: 1 }] },
  { date: "2026-04-13", entries: [{ activityId: "gym", count: 1 }, { activityId: "running", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-14", entries: [{ activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "driving-license", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-04-15", entries: [{ activityId: "abs", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-16", entries: [{ activityId: "gym", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "expressions", count: 1 }] },
  { date: "2026-04-17", entries: [{ activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "guitar", count: 1 }, { activityId: "meditation", count: 1 }] },
  { date: "2026-04-18", entries: [{ activityId: "stretching", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "singing", count: 1 }, { activityId: "nature", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-19", entries: [{ activityId: "cheat", count: 1 }, { activityId: "doomscroll", count: 1 }] },
  { date: "2026-04-20", entries: [{ activityId: "gym", count: 1 }, { activityId: "running", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-21", entries: [{ activityId: "abs", count: 1 }, { activityId: "language", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-04-22", entries: [{ activityId: "running", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "guitar", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-23", entries: [{ activityId: "gym", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "expressions", count: 1 }] },
  { date: "2026-04-24", entries: [{ activityId: "running", count: 1 }, { activityId: "language", count: 1 }, { activityId: "driving-license", count: 1 }, { activityId: "nature", count: 1 }] },
  { date: "2026-04-25", entries: [{ activityId: "abs", count: 1 }, { activityId: "stretching", count: 1 }, { activityId: "reading", count: 1 }, { activityId: "singing", count: 1 }, { activityId: "journaling", count: 1 }] },
  { date: "2026-04-26", entries: [{ activityId: "gym", count: 1 }, { activityId: "deep-work", count: 1 }, { activityId: "meditation", count: 1 }, { activityId: "diction", count: 1 }, { activityId: "nature", count: 1 }] },
];
